In [59]:
import geopandas as gpd
from os import listdir
import time
import pandas as pd
from shapely.geometry import Point, Polygon, MultiPolygon, LinearRing
import numpy as np

In [6]:
# Function definitions

# Function "log" makes a log with the added string, and mark it with the current time
def log(s):
    print('[' + time.strftime('%a %H:%M:%S') + '] ' + s)

In [176]:
osmDir = 'C:/Users/kasina/Dropbox/Python tutorial/West Nile virus/map'

#put the shp filenames into a list
shapeFiles = [f for f in listdir(osmDir) if f.endswith('.shp')] 

#the 2nd and 3rd part of the name is the type of the shape file, let's put them into a list
shapeTypes = [(i.split("_")[3]) for i in shapeFiles] 

# Create a cellShapes GeoPandas DataFrame with reading all the cellshape files
cellShapes = None

log("Start reading shape files...")
for i in range(len(shapeFiles)):
    tmp = gpd.read_file(osmDir+"\\"+shapeFiles[i]) #if we use Lynux, we should use "/" instead of "\\"
    tmp['Shape_Type'] = shapeTypes[i]
    if cellShapes is not None:
        cellShapes = cellShapes.append(tmp)
    else:
        cellShapes = tmp
log("Finished reading shape files...")

cellShapes.head()

[Sat 16:37:09] Start reading shape files...
[Sat 16:47:36] Finished reading shape files...

,Shape_Type,access,addr:city,addr:inclu,addr:postc,addr:stree,admin_leve,area,bridge,class,...,id,name,oneway,osm_id,population,ref,service,tunnel,type,z_order
0,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,1.0,Merrionette Park,NaN,-122049.0,NaN,NaN,NaN,NaN,administrative,NaN
1,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,2.0,Evergreen Park,NaN,-122050.0,NaN,NaN,NaN,NaN,administrative,NaN
2,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,3.0,Schiller Park,NaN,-122051.0,NaN,NaN,NaN,NaN,administrative,NaN
3,admin.shp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,Preston Heights,NaN,-122033.0,NaN,NaN,NaN,NaN,administrative,NaN
4,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,5.0,Lincolnwood,NaN,-122052.0,NaN,NaN,NaN,NaN,administrative,NaN

In [177]:
print(cellShapes.geometry.type.value_counts())

Polygon               953345
LineString            411016
Point                  56170
MultiPolygon             224
GeometryCollection         2
dtype: int64

In [178]:
cellShapes1 = cellShapes[cellShapes.geometry.type == 'Polygon']

In [180]:
print(cellShapes1.geometry.type.value_counts())

Polygon    953345
dtype: int64

In [186]:
cellShapes1.reset_index(drop=True, inplace=True)
cellShapes1

,Shape_Type,access,addr:city,addr:inclu,addr:postc,addr:stree,admin_leve,area,bridge,class,...,id,name,oneway,osm_id,population,ref,service,tunnel,type,z_order
0,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,1.0,Merrionette Park,NaN,-122049.0,NaN,NaN,NaN,NaN,administrative,NaN
1,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,2.0,Evergreen Park,NaN,-122050.0,NaN,NaN,NaN,NaN,administrative,NaN
2,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,3.0,Schiller Park,NaN,-122051.0,NaN,NaN,NaN,NaN,administrative,NaN
3,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,5.0,Lincolnwood,NaN,-122052.0,NaN,NaN,NaN,NaN,administrative,NaN
4,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,6.0,Hometown,NaN,-121470.0,NaN,NaN,NaN,NaN,administrative,NaN
5,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,7.0,Rockdale,NaN,-122032.0,NaN,NaN,NaN,NaN,administrative,NaN
6,admin.shp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,Boulder Hill,NaN,-122041.0,NaN,NaN,NaN,NaN,administrative,NaN
7,admin.shp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,Forest Lake,NaN,-122073.0,NaN,NaN,NaN,NaN,administrative,NaN
8,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,10.0,Hinsdale,NaN,-122053.0,NaN,NaN,NaN,NaN,administrative,NaN
9,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,11.0,Elwood,NaN,-122030.0,NaN,NaN,NaN,NaN,administrative,NaN
10,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,12.0,Highwood,NaN,-122065.0,NaN,NaN,NaN,NaN,administrative,NaN
11,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,13.0,Tower Lakes,NaN,-122069.0,NaN,NaN,NaN,NaN,administrative,NaN
12,admin.shp,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,...,14.0,Edison Park,NaN,-122614.0,NaN,NaN,NaN,NaN,administrative,NaN
13,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,15.0,Indian Creek,NaN,-122067.0,NaN,NaN,NaN,NaN,administrative,NaN
14,admin.shp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.0,Ingalls Park,NaN,-122976.0,NaN,NaN,NaN,NaN,administrative,NaN
15,admin.shp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.0,Frankfort Square,NaN,-122974.0,NaN,NaN,NaN,NaN,administrative,NaN
16,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,18.0,Schaumburg,NaN,-122054.0,NaN,NaN,NaN,NaN,administrative,NaN
17,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,19.0,Riverwoods,NaN,-122942.0,NaN,NaN,NaN,NaN,administrative,NaN
18,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,21.0,Sleepy Hollow,NaN,-122983.0,NaN,NaN,NaN,NaN,administrative,NaN
19,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,22.0,Lake Forest,NaN,-122071.0,NaN,NaN,NaN,NaN,administrative,NaN
20,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,23.0,Trout Valley,NaN,-123050.0,NaN,NaN,NaN,NaN,administrative,NaN
21,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,24.0,Oakwood Hills,NaN,-123069.0,NaN,NaN,NaN,NaN,administrative,NaN
22,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,25.0,Gilberts,NaN,-122984.0,NaN,NaN,NaN,NaN,administrative,NaN
23,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,26.0,West Dundee,NaN,-122986.0,NaN,NaN,NaN,NaN,administrative,NaN
24,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,27.0,Cary,NaN,-123051.0,NaN,NaN,NaN,NaN,administrative,NaN
25,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,28.0,Burr Ridge,NaN,-122048.0,NaN,NaN,NaN,NaN,administrative,NaN
26,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,29.0,Bellwood,NaN,-123124.0,NaN,NaN,NaN,NaN,administrative,NaN
27,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,30.0,Justice,NaN,-123119.0,NaN,NaN,NaN,NaN,administrative,NaN
28,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,31.0,Cicero,NaN,-123129.0,NaN,NaN,NaN,NaN,administrative,NaN
29,admin.shp,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,32.0,Port Barrington,NaN,-122068.0,NaN,NaN,NaN,NaN,administrative,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953315,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,9.729340e-07,NaN,NaN,...,11455.0,None,NaN,551422909.0,NaN,NaN,NaN,NaN,water,NaN
953316,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.859610e-06,NaN,NaN,...,11456.0,None,NaN,551422911.0,NaN,NaN,NaN,NaN,water,NaN
953317,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,4.492520e-07,NaN,NaN,...,11457.0,None,NaN,551422915.0,NaN,NaN,NaN,NaN,water,NaN
953318,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.824500e-05,NaN,NaN,...,11458.0,None,NaN,551304778.0,NaN,NaN,NaN,NaN,water,NaN
953319,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,8.748580e-07,NaN,NaN,...,11459.0,None,NaN,551492141.0,NaN,NaN,NaN,NaN,water,NaN
953320,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.284780e-06,NaN,NaN,...,11460.0,None,NaN,551507954.0,NaN,NaN,NaN,NaN,water,NaN
953321,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.508310e-07,NaN,NaN,...,11461.0,None,NaN,551422906.0,NaN,NaN,NaN,NaN,water,NaN
953322,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,6.301440e-07,NaN,NaN,...,11462.0,None,NaN,551713654.0,NaN,NaN,NaN,NaN,water,NaN
953323,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.431290e-06,NaN,NaN,...,11463.0,None,NaN,551713657.0,NaN,NaN,NaN,NaN,water,NaN
953324,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,3.976190e-07,NaN,NaN,...,11464.0,None,NaN,551713922.0,NaN,NaN,NaN,NaN,water,NaN
953325,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,3.483520e-06,NaN,NaN,...,11465.0,None,NaN,551713756.0,NaN,NaN,NaN,NaN,water,NaN
953326,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.835270e-06,NaN,NaN,...,11466.0,None,NaN,551713661.0,NaN,NaN,NaN,NaN,water,NaN
953327,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.777080e-07,NaN,NaN,...,11467.0,None,NaN,551740018.0,NaN,NaN,NaN,NaN,water,NaN
953328,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,3.773060e-07,NaN,NaN,...,11468.0,None,NaN,551422893.0,NaN,NaN,NaN,NaN,water,NaN
953329,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.212730e-07,NaN,NaN,...,11469.0,None,NaN,551740979.0,NaN,NaN,NaN,NaN,water,NaN
953330,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.832730e-07,NaN,NaN,...,11470.0,None,NaN,551785598.0,NaN,NaN,NaN,NaN,water,NaN
953331,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,3.722050e-07,NaN,NaN,...,11471.0,None,NaN,551740029.0,NaN,NaN,NaN,NaN,water,NaN
953332,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,5.851670e-07,NaN,NaN,...,11472.0,None,NaN,552008898.0,NaN,NaN,NaN,NaN,water,NaN
953333,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,5.901210e-07,NaN,NaN,...,11473.0,None,NaN,552008899.0,NaN,NaN,NaN,NaN,water,NaN
953334,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.642280e-07,NaN,NaN,...,11474.0,None,NaN,552009009.0,NaN,NaN,NaN,NaN,water,NaN
953335,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.904080e-07,NaN,NaN,...,11475.0,None,NaN,552009059.0,NaN,NaN,NaN,NaN,water,NaN
953336,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.427400e-07,NaN,NaN,...,11476.0,None,NaN,552009060.0,NaN,NaN,NaN,NaN,water,NaN
953337,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.326780e-07,NaN,NaN,...,11477.0,None,NaN,552009061.0,NaN,NaN,NaN,NaN,water,NaN
953338,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.771130e-07,NaN,NaN,...,11478.0,None,NaN,552009062.0,NaN,NaN,NaN,NaN,water,NaN
953339,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,8.715170e-08,NaN,NaN,...,11479.0,None,NaN,552009063.0,NaN,NaN,NaN,NaN,water,NaN
953340,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,1.413040e-08,NaN,NaN,...,11480.0,None,NaN,552009066.0,NaN,NaN,NaN,NaN,riverbank,NaN
953341,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,2.176370e-06,NaN,NaN,...,11481.0,None,NaN,552009064.0,NaN,NaN,NaN,NaN,water,NaN
953342,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,7.613120e-07,NaN,NaN,...,11482.0,None,NaN,552009065.0,NaN,NaN,NaN,NaN,water,NaN
953343,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,4.823210e-07,NaN,NaN,...,11483.0,None,NaN,552013894.0,NaN,NaN,NaN,NaN,water,NaN
953344,waterareas.shp,NaN,NaN,NaN,NaN,NaN,NaN,3.200010e-07,NaN,NaN,...,11484.0,None,NaN,552031315.0,NaN,NaN,NaN,NaN,water,NaN

In [194]:
train = pd.read_csv('C:/Users/kasina/Dropbox/Python tutorial/West Nile virus/train.csv')
train['lat-long'] = train.apply(lambda row: Point(row['Latitude'], row['Longitude']),axis=1)

In [218]:
train['shape_type'] = np.nan
train['location_type'] = np.nan

In [220]:
log("Start")
for i in range(len(train_ex)):
    for j in range(len(cellShapes1_ex)):
        if cellShapes1_ex['geometry'][j].contains(train_ex['lat-long'][i]):
            train_ex['shape_type'][i] = cellShapes1_ex['Shape_Type'][j]
            train_ex['location_type'][i] = cellShapes1_ex['type'][j]
        else:
            train_ex['shape_type'][i] = 'unknown'
            train_ex['location_type'][i] = 'unknown'
log("Finish")

[Sat 23:12:53] Start

C:\Users\kasina\Anaconda2\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\kasina\Anaconda2\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

[Sat 23:13:38] Finish

In [221]:
log("Start")
for i in range(len(train)):
    for j in range(len(cellShapes1)):
        if cellShapes1['geometry'][j].contains(train['lat-long'][i]):
            train['shape_type'][i] = cellShapes1['Shape_Type'][j]
            train['location_type'][i] = cellShapes1['type'][j]
        else:
            train['shape_type'][i] = 'unknown'
            train['location_type'][i] = 'unknown' 
log("Finish")

[Sat 23:14:24] Start

C:\Users\kasina\Anaconda2\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\kasina\Anaconda2\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
Exception KeyboardInterrupt in 'zmq.backend.cython.message.Frame.__dealloc__' ignored

KeyboardInterrupt:

In [222]:
train

,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,NumMosquitos,WnvPresent,lat-long,shape_type,location_type
0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0,POINT (41.95469 -87.800991),unknown,unknown
1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0,POINT (41.95469 -87.800991),NaN,NaN
2,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,1,0,POINT (41.994991 -87.769279),NaN,NaN
3,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,1,0,POINT (41.974089 -87.82481199999999),NaN,NaN
4,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,4,0,POINT (41.974089 -87.82481199999999),NaN,NaN
5,2007-05-29,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,2,0,POINT (41.9216 -87.666455),NaN,NaN
6,2007-05-29,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,1,0,POINT (41.891118 -87.65449100000001),NaN,NaN
7,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS/RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,1,0,POINT (41.867108 -87.654224),NaN,NaN
8,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,2,0,POINT (41.867108 -87.654224),NaN,NaN
9,2007-05-29,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8,1,0,POINT (41.896282 -87.655232),NaN,NaN
10,2007-05-29,"2100 North Stave Street, Chicago, IL 60647, USA",CULEX PIPIENS/RESTUANS,21,N STAVE ST,T050,"2100 N STAVE ST, Chicago, IL",41.919343,-87.694259,8,1,0,POINT (41.919343 -87.694259),NaN,NaN
11,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,8,2,0,POINT (41.921965 -87.632085),NaN,NaN
12,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,8,3,0,POINT (41.921965 -87.632085),NaN,NaN
13,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX PIPIENS/RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,8,1,0,POINT (41.688324 -87.676709),NaN,NaN
14,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,8,1,0,POINT (41.688324 -87.676709),NaN,NaN
15,2007-05-29,"1100 South Peoria Street, Chicago, IL 60608, USA",CULEX RESTUANS,11,S PEORIA ST,T091,"1100 S PEORIA ST, Chicago, IL",41.862292,-87.648860,8,1,0,POINT (41.862292 -87.64886),NaN,NaN
16,2007-05-29,"1700 West 95th Street, Chicago, IL 60643, USA",CULEX RESTUANS,17,W 95TH ST,T094,"1700 W 95TH ST, Chicago, IL",41.720848,-87.666014,9,3,0,POINT (41.720848 -87.666014),NaN,NaN
17,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,5,0,POINT (41.731922 -87.67751199999999),NaN,NaN
18,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX PIPIENS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,1,0,POINT (41.731922 -87.67751199999999),NaN,NaN
19,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX PIPIENS/RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,5,1,0,POINT (41.891126 -87.61156),NaN,NaN
20,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,5,2,0,POINT (41.891126 -87.61156),NaN,NaN
21,2007-05-29,"6500 North Oak Park Avenue, Chicago, IL 60631,...",CULEX PIPIENS/RESTUANS,65,N OAK PARK AVE,T143,"6500 N OAK PARK AVE, Chicago, IL",41.999129,-87.795585,8,1,0,POINT (41.999129 -87.795585),NaN,NaN
22,2007-05-29,"7500 North Oakley Avenue, Chicago, IL 60645, USA",CULEX PIPIENS/RESTUANS,75,N OAKLEY AVE,T148,"7500 N OAKLEY AVE, Chicago, IL",42.017430,-87.687769,8,1,0,POINT (42.01743 -87.68776899999999),NaN,NaN
23,2007-05-29,"1500 North Long Avenue, Chicago, IL 60651, USA",CULEX RESTUANS,15,N LONG AVE,T153,"1500 N LONG AVE, Chicago, IL",41.907645,-87.760886,8,1,0,POINT (41.907645 -87.760886),NaN,NaN
24,2007-05-29,"8900 South Carpenter Street, Chicago, IL 60620...",CULEX RESTUANS,89,S CARPENTER ST,T159,"8900 S CARPENTER ST, Chicago, IL",41.732984,-87.649642,8,1,0,POINT (41.732984 -87.649642),NaN,NaN
25,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,3,0,POINT (41.95469 -87.800991),NaN,NaN
26,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,5,0,POINT (41.95469 -87.800991),NaN,NaN
27,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0,POINT (41.95469 -87.800991),NaN,NaN
28,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,1,0,POINT (41.974089 -87.82481199999999),NaN,NaN
29,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,2,0,POINT (41.974089 -87.82481199999999),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,2,0,POINT (41.750498 -87.605294),NaN,NaN
10477,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,1,0,POINT (41.750498 -87.605294),NaN,NaN
10478,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,1,0,POINT (41.750498 -87.605294),NaN,NaN
10479,2013-09-26,"5800 North Pulaski Road, Chicago, IL 60646, USA",CULEX PIPIENS,58,N PULASKI RD,T027,"5800 N PULASKI RD, Chicago, IL",41.984809,-87.728492,8,5,0,POINT (41.98480900000001 -87.728492),NaN,NaN
10480,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS/RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,5,0,POINT (41.659112 -87.53869300000001),NaN,NaN
10481,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,5,0,POINT (41.659112 -87.53869300000001),NaN,NaN
10482,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,4,0,POINT (41.659112 -87.53869300000001),NaN,NaN
10483,2013-09-26,"9100 West Higgins Road, Rosemont, IL 60018, USA",CULEX RESTUANS,91,W HIGGINS RD,T009,"9100 W HIGGINS RD, Chicago, IL",41.992478,-87.862995,8,1,0,POINT (41.99247800000001 -87.862995),NaN,NaN
10484,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS/RESTUANS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,39,1,POINT (41.974689 -87.890615),NaN,NaN
10485,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS/RESTUANS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,4,0,POINT (41.974689 -87.890615),NaN,NaN
10486,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,16,0,POINT (41.974689 -87.890615),NaN,NaN
10487,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,9,0,POINT (41.974689 -87.890615),NaN,NaN
10488,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,11,0,POINT (41.974689 -87.890615),NaN,NaN
10489,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,1,0,POINT (41.974689 -87.890615),NaN,NaN
10490,2013-09-26,"4800 West Montana Street, Chicago, IL 60639, USA",CULEX PIPIENS/RESTUANS,48,W MONTANA ST,T222,"4800 W MONTANA ST, Chicago, IL",41.925198,-87.746381,8,1,0,POINT (41.925198 -87.746381),NaN,NaN
10491,2013-09-26,"5100 North Mont Clare Avenue, Chicago, IL 6065...",CULEX PIPIENS/RESTUANS,51,N MONT CLARE AVE,T223,"5100 N MONT CLARE AVE, Chicago, IL",41.973845,-87.805059,9,11,0,POINT (41.973845 -87.805059),NaN,NaN
10492,2013-09-26,"5100 North Mont Clare Avenue, Chicago, IL 6065...",CULEX PIPIENS,51,N MONT CLARE AVE,T223,"5100 N MONT CLARE AVE, Chicago, IL",41.973845,-87.805059,9,1,0,POINT (41.973845 -87.805059),NaN,NaN
10493,2013-09-26,"8200 South Kostner Avenue, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,82,S KOSTNER AVE,T225,"8200 S KOSTNER AVE, Chicago, IL",41.743402,-87.731435,8,3,0,POINT (41.743402 -87.73143500000001),NaN,NaN
10494,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,5,7,0,POINT (41.728495 -87.60096300000001),NaN,NaN
10495,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,5,1,0,POINT (41.728495 -87.60096300000001),NaN,NaN
10496,2013-09-26,"1700 West Addison Street, Chicago, IL 60613, USA",CULEX PIPIENS/RESTUANS,17,W ADDISON ST,T224,"1700 W ADDISON ST, Chicago, IL",41.947227,-87.671457,9,3,0,POINT (41.94722700000001 -87.67145699999999),NaN,NaN
10497,2013-09-26,"West Garfield Boulevard, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,90,W GARFIELD BLVD,T226,"9000 W GARFIELD BLVD, Chicago, IL",41.793818,-87.654234,5,8,0,POINT (41.793818 -87.654234),NaN,NaN
10498,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS/RESTUANS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,9,13,0,POINT (41.904194 -87.75615500000001),NaN,NaN
10499,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,9,5,0,POINT (41.904194 -87.75615500000001),NaN,NaN
10500,2013-09-26,"3900 North Springfield Avenue, Chicago, IL 606...",CULEX PIPIENS/RESTUANS,39,N SPRINGFIELD AVE,T228,"3900 N SPRINGFIELD AVE, Chicago, IL",41.951866,-87.725057,8,3,0,POINT (41.951866 -87.72505699999999),NaN,NaN
10501,2013-09-26,"5100 West 72nd Street, Chicago, IL 60638, USA",CULEX PIPIENS/RESTUANS,51,W 72ND ST,T035,"5100 W 72ND ST, Chicago, IL",41.763733,-87.742302,8,6,1,POINT (41.763733 -87.742302),NaN,NaN
10502,2013-09-26,"5800 North Ridge Avenue, Chicago, IL 60660, USA",CULEX PIPIENS/RESTUANS,58,N RIDGE AVE,T231,"5800 N RIDGE AVE, Chicago, IL",41.987280,-87.666066,8,5,0,POINT (41.98728 -87.666066),NaN,NaN
10503,2013-09-26,"1700 North Ashland Avenue, Chicago, IL 60622, USA",CULEX PIPIENS/RESTUANS,17,N ASHLAND AVE,T232,"1700 N ASHLAND AVE, Chicago, IL",41.912563,-87.668055,9,1,0,POINT (41.912563 -87.66805500000001),NaN,NaN
10504,2013-09-26,"7100 North Harlem Avenue, Chicago, IL 60631, USA",CULEX PIPIENS/RESTUANS,71,N HARLEM AVE,T233,"7100 N HARLEM AVE, Chicago, IL",42.009876,-87.807277,9,5,0,POINT (42.009876 -87.807277),NaN,NaN
10505,2013-09-26,"4200 West 65th Street, Chicago, IL 60621, USA",CULEX PIPIENS/RESTUANS,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,8,1,0,POINT (41.776428 -87.627096),NaN,NaN